(function(){
  function $(id){return document.getElementById(id)}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(ch){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch]})}
  function client(){try{if(window.sb&&window.sb.from)return window.sb;if(window.supabaseClient&&window.supabaseClient.from)return window.supabaseClient;if(window.getSupabase){var c=window.getSupabase();if(c&&c.from)return c}}catch(e){}return null}
  function ensureResponseBox(){var box=$('mh2AiResponse');if(box)return box;var row=document.querySelector('.mh2-ai-input-row');box=document.createElement('div');box.id='mh2AiResponse';box.className='mh2-ai-response';box.setAttribute('aria-live','polite');if(row&&row.parentNode)row.parentNode.insertBefore(box,row.nextSibling);return box}
  function show(html){var box=ensureResponseBox();box.innerHTML=html;box.classList.add('is-visible')}
  function getCommunity(){var sel=$('zummeeCommunitySelect'),id='',name='';if(sel&&sel.selectedIndex>=0){id=String(sel.value||'').trim();name=String(sel.options[sel.selectedIndex].textContent||'').trim()}id=id||String(window.currentCommunityId||window.activeCommunityId||localStorage.getItem('activeCommunityId')||localStorage.getItem('zummee_selected_community_id')||localStorage.getItem('currentCommunityId')||'').trim();name=name||String(window.currentCommunityName||localStorage.getItem('currentCommunityName')||localStorage.getItem('zummeeCurrentCommunityName')||'').trim();return{id:id,name:name}}
  async function getUserContext(){var out={userId:String(localStorage.getItem('zummee_user_id_v1')||localStorage.getItem('userId')||'').trim(),companyId:String(localStorage.getItem('zummee_company_id')||localStorage.getItem('company_id')||'').trim(),name:String(localStorage.getItem('zummee_user_name')||localStorage.getItem('userName')||'').trim(),email:String(localStorage.getItem('zummee_user_email')||localStorage.getItem('userEmail')||'').trim()};var sb=client();try{if(sb&&sb.auth){var u=await sb.auth.getUser();if(u&&u.data&&u.data.user){out.userId=out.userId||u.data.user.id;out.email=out.email||u.data.user.email}}}catch(e){}try{if(sb&&out.userId){var r=await sb.from('profiles').select('company_id,full_name,name,email').eq('id',out.userId).maybeSingle();if(r&&!r.error&&r.data){out.companyId=out.companyId||String(r.data.company_id||'');out.name=out.name||String(r.data.full_name||r.data.name||'');out.email=out.email||String(r.data.email||out.email||'')}}}catch(e){}return out}
  function monthIndex(m){return{jan:0,january:0,feb:1,february:1,mar:2,march:2,apr:3,april:3,may:4,jun:5,june:5,jul:6,july:6,aug:7,august:7,sep:8,sept:8,september:8,oct:9,october:9,nov:10,november:10,dec:11,december:11}[String(m||'').toLowerCase()]}
  function isoDate(d){var z=function(n){return String(n).padStart(2,'0')};return d.getFullYear()+'-'+z(d.getMonth()+1)+'-'+z(d.getDate())}
  function parseDate(text){text=String(text||'').toLowerCase();var now=new Date();var m=text.match(/\b(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t)?(?:ember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)\s+(\d{1,2})(?:st|nd|rd|th)?(?:,?\s*(\d{4}))?/i);if(m){var yr=m[3]?parseInt(m[3],10):now.getFullYear();var d=new Date(yr,monthIndex(m[1]),parseInt(m[2],10));if(d<new Date(now.getFullYear(),now.getMonth(),now.getDate())&&!m[3])d.setFullYear(yr+1);return isoDate(d)}m=text.match(/\b(\d{1,2})[\/\-](\d{1,2})(?:[\/\-](\d{2,4}))?\b/);if(m){var yr2=m[3]?parseInt(m[3],10):now.getFullYear();if(yr2<100)yr2+=2000;return isoDate(new Date(yr2,parseInt(m[1],10)-1,parseInt(m[2],10)))}if(/\btomorrow\b/.test(text)){var t=new Date(now);t.setDate(t.getDate()+1);return isoDate(t)}var days={sunday:0,monday:1,tuesday:2,wednesday:3,thursday:4,friday:5,saturday:6};m=text.match(/\bnext\s+(sunday|monday|tuesday|wednesday|thursday|friday|saturday)\b/);if(m){var target=days[m[1]],dd=new Date(now),add=(target-dd.getDay()+7)%7;if(add===0)add=7;dd.setDate(dd.getDate()+add);return isoDate(dd)}return ''}
  function parseTime(text){var m=String(text||'').match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/i);if(!m)return '';var h=parseInt(m[1],10),min=m[2]||'00',ap=m[3].toLowerCase();if(ap==='pm'&&h<12)h+=12;if(ap==='am'&&h===12)h=0;return String(h).padStart(2,'0')+':'+String(min).padStart(2,'0')}
  function cleanTitle(text){var t=String(text||'').replace(/\b(schedule|add|create|put|calendar|community|board|my|personal|for|on|at|remind me about|reminder)\b/ig,' ').replace(/\b(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t)?(?:ember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)\s+\d{1,2}(?:st|nd|rd|th)?(?:,?\s*\d{4})?/ig,' ').replace(/\b\d{1,2}[:\d]*\s*(am|pm)\b/ig,' ').replace(/\s+/g,' ').trim();if(!t||t.length<3)t='Community follow-up';return t.charAt(0).toUpperCase()+t.slice(1)}
  function isSchedule(text){return /\b(schedule|calendar|add.*date|meeting|remind me|reminder|event)\b/i.test(text)}
  function showScheduler(text){var date=parseDate(text),time=parseTime(text),title=cleanTitle(text),comm=getCommunity();if(!date){show('<div><strong>I can schedule that.</strong></div><div class="mh2-ai-small">Please include a clear date, like “May 1 at 6 PM.”</div>');return}var pretty=new Date(date+'T00:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});show('<div><strong>Ready to schedule:</strong> '+esc(title)+'</div><div class="mh2-ai-small">Community: '+esc(comm.name||'Selected community')+' • Date: '+esc(pretty)+(time?' • Time: '+esc(time):'')+'</div><div class="mh2-ai-confirm-row"><button class="mh2-ai-action-btn primary" data-schedule-target="community">Add to Community Calendar</button><button class="mh2-ai-action-btn" data-schedule-target="personal">Add to My Calendar</button><button class="mh2-ai-action-btn danger" data-schedule-target="cancel">Cancel</button></div>');window.__mh2PendingAiSchedule={title:title,date:date,time:time,notes:'Created from Manager Hub AI Assistant: '+text,community:comm}}
  async function addSchedule(target){var pending=window.__mh2PendingAiSchedule;if(!pending)return;if(target==='cancel'){show('<span class="mh2-ai-status-bad">Canceled.</span>');return}var sb=client();if(!sb){show('<span class="mh2-ai-status-bad">Supabase is not ready yet.</span>');return}var user=await getUserContext(),comm=pending.community||getCommunity();try{if(target==='personal'){var pr=await sb.from('manager_calendar_events').insert({company_id:user.companyId||null,community_id:comm.id||null,manager_user_id:user.userId||null,title:pending.title,event_date:pending.date,event_time:pending.time||null,notes:pending.notes,source:'ai_assistant'}).select('id').maybeSingle();if(pr.error)throw pr.error;try{await sb.from('manager_reminders').insert({community_id:comm.id||null,title:pending.title,reminder_type:'personal_calendar',reminder_date:pending.date,reminder_time:pending.time||null,source:'ai_assistant',source_id:pr.data&&pr.data.id||null,metadata:{notes:pending.notes,calendar:'personal'}})}catch(e){}show('<span class="mh2-ai-status-ok">Saved to your personal manager calendar.</span>')}else{var startsAt=pending.time?new Date(pending.date+'T'+pending.time+':00'):new Date(pending.date+'T00:00:00');var cr=await sb.from('CommunityCalendarEvents').insert({company_id:user.companyId||null,community_id:comm.id||null,title:pending.title,location:'',notes:pending.notes,starts_at:startsAt.toISOString()}).select('id').maybeSingle();if(cr.error)throw cr.error;try{await sb.from('notification_events').insert({community_id:comm.id||null,event_type:'calendar_event',priority:'attention',title:'Calendar event scheduled',message:'Calendar event scheduled: '+pending.title,link_url:'board_member_hub.html',source_table:'CommunityCalendarEvents',source_id:cr.data&&cr.data.id||null,metadata:{title:pending.title,date:pending.date,time:pending.time||null,source:'ai_assistant'}})}catch(e){}try{await sb.from('manager_reminders').insert({community_id:comm.id||null,title:pending.title,reminder_type:'calendar_event',reminder_date:pending.date,reminder_time:pending.time||null,source:'ai_assistant',source_id:cr.data&&cr.data.id||null,metadata:{notes:pending.notes,calendar:'community'}})}catch(e){}show('<span class="mh2-ai-status-ok">Saved to the community / Board Member Hub calendar.</span>')}}catch(e){console.error(e);show('<span class="mh2-ai-status-bad">Could not save the calendar item.</span><div class="mh2-ai-small">Run ZUMMEE_AI_ASSISTANT_SCHEDULING_V251_SETUP.sql and confirm the CommunityCalendarEvents table exists.</div>')}}
  function handleAsk(evt){var input=$('mh2AiPrompt');var text=String(input&&input.value||'').trim();if(!text){if(input)input.focus();return}if(isSchedule(text)){if(evt){evt.preventDefault();evt.stopImmediatePropagation()}showScheduler(text);return}/* let the existing assistant redirect handle non-scheduling */}
  function bind(){ensureResponseBox();var send=$('mh2AiSendBtn'),input=$('mh2AiPrompt');if(send)send.addEventListener('click',handleAsk,true);if(input)input.addEventListener('keydown',function(e){if((e.metaKey||e.ctrlKey)&&e.key==='Enter')handleAsk(e)},true);document.addEventListener('click',function(e){var b=e.target&&e.target.closest&&e.target.closest('[data-schedule-target]');if(!b)return;e.preventDefault();e.stopPropagation();addSchedule(b.getAttribute('data-schedule-target'))},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
