create table if not exists public.preferred_vendors_shared (
  id bigint generated by default as identity primary key,
  company text not null,
  community_id text not null,
  vendors_json jsonb not null default '[]'::jsonb,
  updated_by uuid null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint preferred_vendors_shared_company_community_key unique (company, community_id)
);

create index if not exists preferred_vendors_shared_company_idx
  on public.preferred_vendors_shared (company);

create index if not exists preferred_vendors_shared_community_idx
  on public.preferred_vendors_shared (community_id);

alter table public.preferred_vendors_shared enable row level security;

-- Read access for authenticated staff.
drop policy if exists "preferred vendors shared read" on public.preferred_vendors_shared;
create policy "preferred vendors shared read"
on public.preferred_vendors_shared
for select
using (auth.role() = 'authenticated');

-- Write access for authenticated staff. Tighten later if you want supervisor/admin only.
drop policy if exists "preferred vendors shared write" on public.preferred_vendors_shared;
create policy "preferred vendors shared write"
on public.preferred_vendors_shared
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
