/* Zummee clean rebuild stabilizer v313 */
(function(){
  if(window.__ZUMMEE_CLEAN_BOOT__) return; window.__ZUMMEE_CLEAN_BOOT__=true;
  function s(v){return String(v==null?'':v).trim()}
  function isUuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s(v))}
  function get(k){try{return s(localStorage.getItem(k))}catch(e){return ''}}
  function set(k,v){try{if(s(v)) localStorage.setItem(k,s(v))}catch(e){}}
  window.addEventListener('error',e=>{try{console.error('[Zummee clean boot JS error]',e.message||e.error||e)}catch(_){}});
  window.addEventListener('unhandledrejection',e=>{try{console.error('[Zummee clean boot promise]',e.reason||e)}catch(_){}});
  function clearBadIds(){['zummee_selected_community_id','activeCommunityId','zummeeActiveCommunityId','currentCommunityId','selectedCommunityId'].forEach(k=>{try{let v=get(k); if(v&&!isUuid(v)) localStorage.removeItem(k)}catch(e){}})}
  function findUuidForName(name){name=s(name).toLowerCase(); if(!name)return ''; let sels=document.querySelectorAll('#zummeeCommunitySelect,#communitySelect,#communityDropdown,select[id*=community],select[name*=community],select[data-community-select]'); for(let sel of sels){for(let opt of (sel.options||[])){if(isUuid(opt.value)&&s(opt.textContent).toLowerCase()===name)return s(opt.value)}} return ''}
  function activeId(){for(let k of ['zummee_selected_community_id','activeCommunityId','zummeeActiveCommunityId','currentCommunityId','selectedCommunityId']){let v=get(k); if(isUuid(v))return v} return findUuidForName(get('currentCommunityName')||get('zummeeCurrentCommunityName'))}
  function publishCommunity(id,name){id=s(id); name=s(name); if(!isUuid(id)){let r=findUuidForName(id)||findUuidForName(name); if(r){if(!name)name=id; id=r}} if(!isUuid(id)){if(name){set('currentCommunityName',name);set('zummeeCurrentCommunityName',name)} clearBadIds(); return} ['zummee_selected_community_id','activeCommunityId','zummeeActiveCommunityId','currentCommunityId'].forEach(k=>set(k,id)); if(name){set('currentCommunityName',name);set('zummeeCurrentCommunityName',name)} try{window.currentCommunityId=id;window.activeCommunityId=id;window.selectedCommunityId=id;window.zummeeSelectedCommunityId=id;window.currentCommunityName=name||window.currentCommunityName||''}catch(e){}}
  function wireSelect(sel){if(!sel||sel.__zummeeCleanWired)return; sel.__zummeeCleanWired=true; let stored=activeId(); if(stored&&Array.from(sel.options||[]).some(o=>s(o.value)===stored)) sel.value=stored; if(sel.value){let opt=sel.options&&sel.selectedIndex>=0?sel.options[sel.selectedIndex]:null; publishCommunity(sel.value,opt?opt.textContent:'')} sel.addEventListener('change',()=>{let opt=sel.options&&sel.selectedIndex>=0?sel.options[sel.selectedIndex]:null; publishCommunity(sel.value,opt?opt.textContent:'')})}
  function wire(){clearBadIds(); ['zummeeCommunitySelect','communitySelect','communityDropdown'].forEach(id=>wireSelect(document.getElementById(id))); document.querySelectorAll('select[id*=community],select[name*=community],select[data-community-select]').forEach(wireSelect); let id=activeId(); if(id)publishCommunity(id,get('currentCommunityName')||get('zummeeCurrentCommunityName'))}
  window.zummeeGetSB=async function(){try{if(window.supabaseClient&&typeof window.supabaseClient.from==='function')return window.supabaseClient}catch(e){} try{if(window.sb&&typeof window.sb.from==='function')return window.sb}catch(e){} try{if(window.ensureSupabase){let c=await window.ensureSupabase(); if(c&&typeof c.from==='function')return c}}catch(e){} try{if(window.ensureSupabaseSync){let c=window.ensureSupabaseSync(); if(c&&typeof c.from==='function')return c}}catch(e){} return null};
  window.zummeeDispatchCommunityRefresh=function(){wire(); let id=activeId(); if(!id)return; try{document.dispatchEvent(new CustomEvent('community:changed',{detail:{community_id:id}}))}catch(e){} try{window.dispatchEvent(new CustomEvent('community:changed',{detail:{community_id:id}}))}catch(e){}};
  function boot(){wire(); setTimeout(wire,250); setTimeout(wire,1000); setTimeout(()=>{try{window.zummeeDispatchCommunityRefresh()}catch(e){}},1200)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();
